<?php
if (!isset ($_SESSION)) {
	session_start();
}
//	include $_SERVER['DOCUMENT_ROOT'] ."/libs/qrcode/qrcode.php";
require_once $_SERVER['DOCUMENT_ROOT'] . "/classes/class.staff.php";
//require_once $_SERVER['DOCUMENT_ROOT'] . "/classes/BarCodeFile.php";
require_once $_SERVER['DOCUMENT_ROOT'] . "/classes/DAOs/PatientDemographDAO.php";
require_once $_SERVER['DOCUMENT_ROOT'] . "/classes/DAOs/ClinicDAO.php";


//$staff = new StaffManager();
//$hosp = $staff->getHospitalInfo($staff->getStaffHospitalID($_SESSION['staffID']));
$hosp = (new ClinicDAO())->getClinic(1)->getName();
//$server = ($_SERVER['HTTPS'] ? "https://" : "http://") . $_SERVER['HTTP_HOST'] . '/patient_profile.php?id=' . $_GET['pid'];

$pat = (new PatientDemographDAO())->getPatient($_GET['pid'], false, null, null);
$code = $pat->getId();

//$url = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' ? "https://" : "http://") . $_SERVER['HTTP_HOST'] . "/barcode.php?text=$code";
//$imdata = base64_encode(file_get_contents($url));
//$img_ = '<img src="data:image/png;base64,' . ($imdata) . '" />';
////use this one in case
//require_once $_SERVER['DOCUMENT_ROOT'] . '/libs/php-barcode-generator-master/src/BarcodeGenerator.php';
//require_once $_SERVER['DOCUMENT_ROOT'] . '/libs/php-barcode-generator-master/src/BarcodeGeneratorJPG.php';
//$generator = new Picqer\Barcode\BarcodeGeneratorJPG();

//$img_ = '<img style="height:100%" src="data:image/png;base64,' . base64_encode( $generator->getBarcode($code, $generator::TYPE_CODE_128)) . '" />';

?>
<script type="text/javascript" src="/js/JsBarcode.all.min.js"></script>
<script type="text/javascript" src="/assets/jquery-print/jQuery.print.js"></script>
<link rel="stylesheet" href="/style/def.css" media="print"/>
<link href="/style/bootstrap.css" rel="stylesheet" type="text/css" media="print"/>
<script>
	$(document).ready(function () {
		JsBarcode("#barcode").init();
		//JsBarcode(".barcode").init();
		$("#idc").live("click", function (e) {
			if (!e.handled) {
				$("#idCard").print({
					addGlobalStyles: true,
					stylesheet: null,
					rejectWindow: true,
					noPrintSelector: ".no-print",
					iframe: true,
					append: "Generated by MedicPlus"
				});
				e.handled = true;
			}
		});
	});
</script>

<?php for ($i = 1; $i <= 0; $i++) { ?>
		<img class="barcode"
		     alt="<?= 'PR' . str_pad($i, 5, "0", STR_PAD_LEFT) ?>.png"
		     jsbarcode-text="<?= 'PR/' . str_pad($i, 5, "0", STR_PAD_LEFT) ?>"
		     jsbarcode-width="1"
		     jsbarcode-height="20"
		     jsbarcode-format="CODE39"
		     jsbarcode-value="<?= 'PR/' . str_pad($i, 5, "0", STR_PAD_LEFT) ?>"
		     jsbarcode-textmargin="0"
		     jsbarcode-fontsize="10"/>
<?php } ?>
<div id="idCard">
	<table class="table table-borderless">
		<tr>
			<td class="text-center"><?= $pat->getFullname() ?></td>
		</tr>
		<tr>
			<td class="text-center">
				<svg id="barcode"
				     jsbarcode-text="<?= $pat->getFullname() ?>"
				     jsbarcode-width="1"
				     jsbarcode-height="60"
				     jsbarcode-format="CODE39"
				     jsbarcode-value="<?= $pat->getId() ?>"
				     jsbarcode-textmargin="0"
				     jsbarcode-fontoptions="italic"></svg>
			</td>
		</tr>
		<tr>
			<td class="text-center fadedText"><em>Issued At: <?php echo $hosp ?></em></td>
		</tr>
	</table>

	<a href="javascript:void(0)" class="pull-right print no-print action" id="idc"><i class="icon-print"></i> Print</a>

	<a class="pull-right print no-print action" href="/pdf.php?page=<?= urlencode($_SERVER['REQUEST_URI']) ?>" style="margin-right:5px">PDF</a>
</div>

