<?php
/**
 * Created by PhpStorm.
 * User: robot
 * Date: 4/4/16
 * Time: 10:47 PM
 */
//$_GET['id'];
//$_GET['type']; ip || op
?>
<?php
/**
 * Created by PhpStorm.
 * User: robot
 * Date: 4/5/16
 * Time: 1:45 PM
 */
require_once $_SERVER['DOCUMENT_ROOT'] . '/classes/DAOs/PatientDemographDAO.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/classes/DAOs/StaffDirectoryDAO.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/classes/DAOs/EstimatedBillLineDAO.php';
require_once $_SERVER['DOCUMENT_ROOT'] .'/classes/DAOs/EstimatedBillsDAO.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/classes/DAOs/InPatientDAO.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/classes/DAOs/InsuranceBillableItemDAO.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/classes/DAOs/BillSourceDAO.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/classes/DAOs/PatientProcedureDAO.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/classes/DAOs/ClinicDAO.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/classes/Clinic.php';
require_once $_SERVER['DOCUMENT_ROOT'] .'/classes/EstimatedBillLine.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/classes/EstimatedBills.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/classes/class.config.main.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/functions/utils.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/functions/func.php';

$pageSize = 10;
$page = isset($_GET['page']) ? $_GET['page'] : 0;

$estimated_bill_lines = (new EstimatedBillLineDAO())->getEstimatedBillLineById($_GET['id']);
$estimated_bill = (new EstimatedBillsDAO())->getEstimatedBillById($_GET['id']);

$procedures = (new PatientProcedureDAO())->getPatientProcedures($_GET['pid'],null,null,$page,$pageSize,null,null);
$patient = (new PatientDemographDAO())->getPatient($_GET['pid'], true);
$code = $estimated_bill->getEsCode();

$url = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' ? "https://" : "http://") . $_SERVER['HTTP_HOST'] . "/barcode.php?text=$code";

?>
<!DOCTYPE html>
<html moznomarginboxes mozdisallowselectionprint>
<head>

<!--    <script type="text/javascript" src="/js/JsBarcode.all.min.js"></script>-->
<!--    <script type="text/javascript" src="/assets/jquery-print/jQuery.print.js"></script>-->
<!--    <link rel="stylesheet" href="/style/def.css" media="print"/>-->
<!--    <link href="/style/bootstrap.css" rel="stylesheet" type="text/css" media="print"/>-->

    <meta charset="UTF-8">

    <script src="/js/jquery-2.1.1.min.js"></script>
    <script src="/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="/assets/jquery-print/jQuery.print.js" type="text/javascript"></script>
    <link href="/style/def.css" rel="stylesheet" type="text/css"/>
    <link href="/style/bootstrap.css" rel="stylesheet" type="text/css"/>
    <link href="/style/font-awesome.css" rel="stylesheet" type="text/css"/>
    <script src="/assets/blockUI/jquery.blockUI.js"></script>
    <link href="/assets/blockUI/growl.ui.css" rel="stylesheet" type="text/css"/>
    <meta name="viewport" content="width=device-width">
<!--    <script>-->
<!--        $(document).ready(function () {-->
<!--            JsBarcode("#barcode").init();-->
<!--                    $("#idCard").print({-->
<!--                        addGlobalStyles: true,-->
<!--                        stylesheet: null,-->
<!--                        rejectWindow: true,-->
<!--                        noPrintSelector: ".no-print",-->
<!--                        iframe: true,-->
<!--                        append: "Generated by MedicPlus"-->
<!--                    });-->
<!--        });-->
<!--    </script>-->
    <style>
        .table-condensed > thead > tr > th, .table-condensed > tbody > tr > th, .table-condensed > tfoot > tr > th, .table-condensed > thead > tr > td, .table-condensed > tbody > tr > td, .table-condensed > tfoot > tr > td {
            padding: 2px !important;
        }

        .table {
            color: #000;
        }

        table, tr, td, th, tbody, thead, tfoot {
            page-break-inside: avoid !important;
        }
        p{
            font-size: 18px;
            font-style: italic;
        }
        .head-foot{
            background-color: #F9F9F9;
            border: solid 5px transparent;
            height: auto;
        }
    </style>
</head>
<body style="margin: 50px 20px;">


<div class="container">


    <?= (new ClinicDAO())->getClinic(1)->getHeader() ?>

    <div class="row-fluid">

        <div class="span4">#<?= $estimated_bill->getEsCode()?></div>
        <div class="span4">&nbsp;</div>
        <div class="span4">
          &nbsp;
        </div>

    </div>

    <table class="table table-bordered table-striped text-capitalize">
        <tr>
            <th>Patient Name</th>
            <td><?= $patient->getFullname() ?></td>
            <th>Gender</th>
            <td><?= $patient->getSex() ?></td>
        </tr>
        <tr>
            <th>Hospital No.</th>
            <td><?= $patient->getId() ?></td>
            <th>NHIS/HMO ID No*:</th>
            <td><?= $patient->getInsurance()->getEnrolleeId() ?></td>
        </tr>
        <tr>
            <th>D.o.B</th>
            <td><?= date("d/M/Y", strtotime($patient->getDateOfBirth())) ?></td>
            <th>Age</th>
            <td><?= $patient->getAge() ?></td>
        </tr>
        <tr>
            <th>HMO</th>
            <td></td>
            <th>Payer No.*</th>
            <td><?= $patient->getInsurance()->getScheme()->getInsurer()->getName() ?></td>
        </tr>
        <tr>
            <th>Company/Office</th>
            <td><?= $patient->getWorkAddress() ?></td>
            <th>Enrollee Type</th>
            <td></td>
        </tr>
        <tr>
            <th>Occupation</th>
            <td><?= $patient->getOccupation() ?></td>
            <th>Email</th>
            <td style="text-transform: initial;"><?= $patient->getEmail() ?></td>
        </tr>
        <tr>
            <th>Address</th>
            <td><?= $patient->getAddress() ?></td>
            <th>Telephone</th>
            <td><?= $patient->getPhoneNumber() ?></td>
        </tr>

    </table>


           <div class="row-fluid head-foot">
               <h2>NOTE:</h2>
            <p>
                <?=$estimated_bill->getNarration()?>.
            </p>
           </div>
        <div class="text-center text-capitalize">
            <h2>DETAILS:</h2>
        </div>
        <div class="row-fluid">
            <div class="fadedText pull-left">Created: <?= $estimated_bill->getDateCreated()?> &nbsp; By: <?= $estimated_bill->getCreatedBy()->getFullName()?></div>

        </div>
        <div class="row-fluid box tight bold">
            <div class="span6">SERVICE</div>
            <div class="span1">QTY</div>
            <div class="span2 amount">UNIT PRICE</div>
            <div class="span3 amount">AMOUNT</div>
        </div>
        <?php
        $tot = 0;
        foreach ($estimated_bill_lines as $es_bill) { //$bill = new Bill;
            if ($es_bill) {
                ?>
                <div class="row-fluid box tight">
                    <div class="span6"><?= $es_bill->getItemDescription() ?></div>
                    <div class="span1"><?= $es_bill->getQuantity() ?></div>
                    <div class="span2 amount">&nbsp;&nbsp;<?= number_format($es_bill->getUnitPrice(), 2) ?></div>
                    <div class="span3 amount"><?=number_format($es_bill->getQuantity() * $es_bill->getUnitPrice(),2)?></div>
                </div>
                <?php
                $tot += $es_bill->getQuantity() * floatval($es_bill->getUnitPrice());
            }
        }
        ?>
        <div class="row-fluid box tight">
            <div class="span8"><b>TOTAL</b></div>
            <div class="span2 amount"><b><?= number_format($tot, 2) ?></b></div>
            <div class="span2 amount">&nbsp;</div>
        </div>

        <div class="row-fluid">
            <div class="span12 amount"><b><?= ucwords((new toWords($tot))->words) ?></b></div>
        </div>

    <div style="margin-bottom: 50px"></div>
    <div class="row-fluid">
        <div class="span6">
<!--            <hr color="#000" style="margin-top: 10px; ">-->
<!--            <div class="text-center">Patient Signature</div>-->
            &nbsp;
        </div>
        <div class="span6">

            <hr color="#000" style="margin-top: 10px;">
            <div class="text-center">Approved By</div>
        </div>
    </div>

    <div class="text-center text-capitalize">
      <h2>ACCOUNT DETAILS:</h2>
    </div>
    <section>
        <div class="row-fluid">
            <div class="span4">
                <div class="e-block">
                    <div class="title">Bank Name</div>
                    <div class="content">Guaranty Trust Bank</div>
                </div>
            </div>
            <div class="span4">
                <div class="e-block">
                    <div class="title">Account Name</div>
                    <div class="content">Cedacrest Orthopaedic Clinic Ltd</div>
                </div>
            </div>
            <div class="span4">
                <div class="e-block">
                    <div class="title">Account Number</div>
                    <div class="content">0078005499</div>
                </div>
            </div>

        </div>
    </section>
    <br><br><br>

    <div class="row-fluid">
        <div class="fadedText pull-left">This document is valid till: <?= $estimated_bill->getValidTill()?></div>

    </div>

   <section style="border-top: solid 1px #bcbcbc; border-bottom: solid 1px #bcbcbc;">
       <div class="row-fluid">
         <p class="fadedText" style="padding: 10px;">
             the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an
             unknown printer took a galley of type and scrambled it to make a type specimen book.
         </p>
       </div>
   </section>
    <div class="row-fluid">
        <div class="fadedText pull-right">
          Printed....<?= date('Y-m-d H:i:s')?>
        </div>

    </div>

    <div style="margin:200px 0 25px">
        <?php if (isset($_GET['reprint'])) { ?>Disclaimer: The insurance details of the patient might have changed and will not be represented accurately at this moment of reprint<?php } ?>
    </div>
    <div class="row-fluid no-print pull-right">
        <div class="span12">
            <a href="/pdf.php?page=<?= urlencode('/billing/estimated_bill_sheet.php?id=' . $_GET['id'] .'&pid='.$_GET['pid']. (isset($_GET['tabular']) ? '&tabular' :'')) ?>"
               class="action">PDF</a>
            <a href="javascript:;" onclick="window.print()" class="action"><i class="icon-print"></i> Print</a>
        </div>
    </div>
</div>

</body>
<script type="text/javascript">
    $(document).ready(function () {
        $('a[href^="/pdf.php"]:first').get(0).click();
        $.blockUI({
            message: '<div class="ball"></div><br><h6 class="fadedText" style="font-size:200%">Generating PDF. Please wait...</h6>',
            css: {
                borderWidth: '0',
                backgroundColor: 'transparent'
            }
        })
    })
</script>
</html>

